### ISSUE TITLE
conversioni

### ISSUE THREAD

**Issue by FabioZTessitore** [EnricoRuggieroB/funzioni#1]
in attesa

**Comment by FabioZTessitore** [comment]
i prototipi di funzione non vanno nel main

**Comment by RuggieroB** [comment]
Domani correggerò 



Inviato da Libero Mail per iOS


martedì 28 maggio 2019, 21:28 +0200 da notifications@github.com  <notifications@github.com>:

**Comment by RuggieroB** [comment]
@FabioZTessitore Corretto!
