### ISSUE TITLE
conversioni2

### ISSUE THREAD

**Issue by FabioZTessitore** [EnricoRuggieroB/funzioni#2]
il programma va bene, ma cerca di prestare un po' di attenzione ai nomi delle variabili. Devono essere significativi

**Comment by RuggieroB** [comment]
Ah... non so come chiamarle... dovrò pensare un bel po’!



Inviato da Libero Mail per iOS


mercoledì 29 maggio 2019, 14:41 +0200 da notifications@github.com  <notifications@github.com>:
